"""add_storygraph_edition_fields

Revision ID: 33dc0561f4c4
Revises: c8a2d7e4f1b9
Create Date: 2026-04-28 08:55:00.379109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33dc0561f4c4'
down_revision: Union[str, Sequence[str], None] = 'c8a2d7e4f1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'storygraph_details' not in inspector.get_table_names():
        op.create_table(
            'storygraph_details',
            sa.Column('abs_id', sa.String(255), primary_key=True),
            sa.Column('storygraph_book_id', sa.String(255), nullable=True),
            sa.Column('storygraph_url', sa.String(1000), nullable=True),
            sa.Column('storygraph_edition_id', sa.String(255), nullable=True),
            sa.Column('storygraph_pages', sa.Integer(), nullable=True),
            sa.Column('isbn', sa.String(255), nullable=True),
            sa.Column('asin', sa.String(255), nullable=True),
            sa.Column('matched_by', sa.String(50), nullable=True),
            sa.ForeignKeyConstraint(['abs_id'], ['books.abs_id'], ondelete='CASCADE'),
        )
    else:
        columns = {col['name'] for col in inspector.get_columns('storygraph_details')}
        with op.batch_alter_table('storygraph_details', schema=None) as batch_op:
            if 'storygraph_edition_id' not in columns:
                batch_op.add_column(sa.Column('storygraph_edition_id', sa.String(length=255), nullable=True))
            if 'storygraph_pages' not in columns:
                batch_op.add_column(sa.Column('storygraph_pages', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storygraph_details', schema=None) as batch_op:
        batch_op.drop_column('storygraph_pages')
        batch_op.drop_column('storygraph_edition_id')

    # ### end Alembic commands ###
